name: priority_boost
description: AI-powered priority management app

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  animations: ^2.0.7
  confetti: ^0.7.0
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true